version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine

  celery:
    build: .
    command: celery -A app.tasks.background_tasks.celery_app worker --loglevel=info
    depends_on:
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_DB: ${postgres_db}
